import { gql } from '@apollo/client';

export const GET_POSTS = gql`
  query GetPosts {
    posts {
      id
      content
      createdAt
      author {
        id
        name
      }
      image
    }
  }
`;

export interface Post {
  id: string;
  content: string;
  createdAt: string;
  author: {
    id: string;
    name: string;
  };
  image?: string | null;
}
